// Declarative config that drives every CRUD module page.
// Each resource: endpoint + columns (table) + fields (form).
// type: text | number | money | date | select | checkbox | percent
// computed columns are read-only (returned by the server's derive fns).

export const LISTS = {
  probability_status: ['Confirmed', 'High Probability', 'Medium Probability', 'Low Probability'],
  payment_category: [
    'Supplier Payment',
    'Salaries',
    'Rent',
    'Government Fees',
    'Commissions',
    'Logistics & Transportation',
    'Installation Costs',
    'Other Expenses',
  ],
  priority: ['Critical', 'High', 'Medium', 'Low'],
  project_status: ['Signed', 'In Progress', 'Delivered', 'Invoiced', 'Collected', 'On Hold'],
  inventory_category: [
    'Cooking',
    'Dishwashing',
    'Preparation',
    'Refrigeration',
    'Stainless Steel',
    'Laundry',
    'Other',
  ],
};

export const RESOURCES = {
  projects: {
    endpoint: '/projects',
    titleKey: 'nav.projects',
    columns: [
      { key: 'name', label: 'Project', type: 'text' },
      { key: 'customer', label: 'Customer', type: 'text' },
      { key: 'contract_value', label: 'Contract Value', type: 'money' },
      { key: 'collected_to_date', label: 'Collected', type: 'money' },
      { key: 'remaining_ar', label: 'Remaining AR', type: 'money', computed: true },
      { key: 'gross_profit_pct', label: 'Expected GP %', type: 'percent100' },
      { key: 'expected_gross_profit', label: 'Expected Gross Profit', type: 'money', computed: true },
      { key: 'actual_cost', label: 'Cost', type: 'money', computed: true },
      { key: 'actual_gp', label: 'GP (Rev−Cost)', type: 'money', computed: true },
      { key: 'actual_gp_pct', label: 'GP %', type: 'percent100', computed: true },
      { key: 'status', label: 'Status', type: 'select', options: LISTS.project_status, pill: true },
      { key: 'progress_pct', label: 'Delivery / Progress %', type: 'number' },
      { key: 'next_billing', label: 'Next Billing', type: 'text' },
      { key: 'expected_collection_date', label: 'Exp. Collection', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'text' },
    ],
  },
  collections: {
    endpoint: '/collections',
    titleKey: 'nav.collections',
    columns: [
      { key: 'project', label: 'Project', type: 'text' },
      { key: 'customer', label: 'Customer', type: 'text' },
      { key: 'amount', label: 'Amount', type: 'money' },
      { key: 'expected_date', label: 'Expected Date', type: 'date' },
      { key: 'probability_pct', label: 'Prob %', type: 'number' },
      { key: 'probability_status', label: 'Probability', type: 'select', options: LISTS.probability_status, pill: true },
      { key: 'invoice_ref', label: 'Invoice Ref', type: 'text' },
      { key: 'confirmed', label: 'Confirmed', type: 'checkbox' },
      { key: 'actual_collection_date', label: 'Actual Date', type: 'date' },
      { key: 'delay_days', label: 'Delay (days)', type: 'number', computed: true },
      { key: 'owner', label: 'Owner', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'text' },
    ],
  },
  payments: {
    endpoint: '/payments',
    titleKey: 'nav.payments',
    columns: [
      { key: 'category', label: 'Category', type: 'select', options: LISTS.payment_category },
      { key: 'supplier', label: 'Supplier/Payee', type: 'text' },
      { key: 'amount', label: 'Amount (excl. VAT)', type: 'money' },
      {
        key: 'vat_rate',
        label: 'VAT Rate',
        type: 'select',
        numeric: true,
        options: [
          { label: '0%', value: 0 },
          { label: '5%', value: 0.05 },
          { label: '10%', value: 0.1 },
          { label: '15%', value: 0.15 },
        ],
      },
      {
        key: 'vat_amount',
        label: 'VAT Amount',
        type: 'money',
        computed: true,
        compute: (f) => Math.round((Number(f.amount) || 0) * (Number(f.vat_rate) || 0) * 100) / 100,
      },
      {
        key: 'total_amount',
        label: 'Total (incl. VAT)',
        type: 'money',
        computed: true,
        compute: (f) => Math.round((Number(f.amount) || 0) * (1 + (Number(f.vat_rate) || 0)) * 100) / 100,
      },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'priority', label: 'Priority', type: 'select', options: LISTS.priority, pill: true },
      { key: 'project_link', label: 'Project Link', type: 'text' },
      { key: 'can_delay', label: 'Can Delay?', type: 'checkbox' },
      { key: 'paid', label: 'Paid?', type: 'checkbox' },
      { key: 'actual_payment_date', label: 'Paid Date', type: 'date' },
      { key: 'owner', label: 'Owner', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'text' },
    ],
  },
  inventory: {
    endpoint: '/inventory',
    titleKey: 'nav.inventory',
    columns: [
      { key: 'category', label: 'Category', type: 'select', options: LISTS.inventory_category },
      { key: 'brand_supplier', label: 'Brand/Supplier', type: 'text' },
      { key: 'item', label: 'Item', type: 'text' },
      { key: 'qty', label: 'Qty', type: 'number' },
      { key: 'unit_cost', label: 'Unit Cost', type: 'money' },
      { key: 'total_cost', label: 'Total Cost', type: 'money', computed: true },
      { key: 'sell_price', label: 'Sell Price', type: 'money' },
      { key: 'potential_revenue', label: 'Potential Rev.', type: 'money', computed: true },
      { key: 'expected_gross_profit', label: 'Exp. Gross', type: 'money', computed: true },
      { key: 'stock_location', label: 'Location', type: 'text' },
      { key: 'funding_source', label: 'Funding', type: 'text' },
      { key: 'linked_project', label: 'Linked Project', type: 'text' },
      { key: 'stock_risk', label: 'Stock Risk', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'text' },
    ],
  },
  'supplier-ledger': {
    endpoint: '/supplier-ledger',
    titleKey: 'nav.supplierLedger',
    columns: [
      { key: 'supplier', label: 'Supplier', type: 'text' },
      { key: 'po', label: 'P.O', type: 'money' },
      { key: 'po_plus_vat', label: 'P.O + VAT', type: 'money', computed: true },
      { key: 'invoiced_amount', label: 'Invoiced', type: 'money' },
      { key: 'paid_amount', label: 'Paid', type: 'money' },
      { key: 'invoice_balance', label: 'Invoice Balance', type: 'money', computed: true },
      { key: 'closing_balance', label: 'Closing Balance', type: 'money', computed: true },
      { key: 'negotiation_action', label: 'Negotiation Action', type: 'text' },
    ],
  },
  'customer-ledger': {
    endpoint: '/customer-ledger',
    titleKey: 'nav.customerLedger',
    columns: [
      { key: 'project_name', label: 'Project Name', type: 'text' },
      { key: 'project_id', label: 'Project ID', type: 'text' },
      { key: 'so', label: 'S.O', type: 'money' },
      { key: 'so_plus_vat', label: 'S.O + VAT', type: 'money', computed: true },
      { key: 'invoiced_amount', label: 'Invoiced', type: 'money' },
      { key: 'paid_amount', label: 'Paid', type: 'money' },
      { key: 'collection_pct', label: 'Collection %', type: 'percent', computed: true },
      { key: 'remaining_total', label: 'Remaining', type: 'money', computed: true },
      { key: 'project_status', label: 'Status', type: 'select', options: LISTS.project_status, pill: true },
      { key: 'notes', label: 'Notes', type: 'text' },
    ],
  },
  'ar-aging': {
    endpoint: '/ar-aging',
    titleKey: 'nav.aging',
    columns: [
      { key: 'customer', label: 'Customer', type: 'text' },
      { key: 'current_amt', label: 'Current', type: 'money' },
      { key: 'd1_30', label: '1-30 Days', type: 'money' },
      { key: 'd31_60', label: '31-60 Days', type: 'money' },
      { key: 'd61_90', label: '61-90 Days', type: 'money' },
      { key: 'd90_plus', label: '>90 Days', type: 'money' },
      { key: 'total', label: 'Total', type: 'money', computed: true },
      { key: 'collection_owner', label: 'Owner', type: 'text' },
      { key: 'action_required', label: 'Action Required', type: 'text' },
    ],
  },
};
